/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public abstract class Mobile {

    private String name;
    private String color;
    private String brand;
    private String message;

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }



    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public abstract void call();

    public static void main(String[] args){

        Mobile iPhone = new iPhone();

        iPhone.setMessage("Call from iPhone");
        iPhone.call();

    }
}
