/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Mobile {
    private String name;
    private String color;
    private String band;

    public void call(String message){
        System.out.println("Message :" + message);
    }
}
