/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public abstract class Mobile {
    private String message;
    private String name;
    private String color;
    private String brand;

    public void setName(String name) {
        this.name = name;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }


    public String getName() {
        return this.name;
    }

    public abstract void call();

    public void specs() {
        System.out.println("name: " + getName() + " color: " + getColor() + " brand: "+getBrand());
    }


    public static void main(String[] args){
        // Story 1
        iPhone iPhone = new iPhone();
        Android android = new Android();

        iPhone.setMessage("Call from iPhone");
        iPhone.call();

        android.setMessage("Call from Android");
        android.call();

        //Story 2
        iPhone.setName("Iphone 13");
        iPhone.setColor("Magenta");
        iPhone.setBrand("Iphone");
        iPhone.specs();

        android.setName("Xiaomi T Pro");
        android.setColor("Magenta");
        android.setBrand("Iphone");
        android.specs();

    }
}
